[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = ["npx pnpm@10.18.3 install --frozen-lockfile"]

[phases.build]
cmds = ["npx pnpm@10.18.3 build"]

[start]
cmd = "npx pnpm@10.18.3 start"
