[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = ["npx -y pnpm@10.18.3 install --frozen-lockfile --prod=false"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start:prod"
